name: awsome-project
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - python=3.11
  - pip
  - geopandas
  - pandas
  - pandas-datareader
  - statsmodels
  - xlrd
  - dask
  - networkx
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - kiwisolver
  - matplotlib
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - geoplot
  - geopy
  - pycountry
  - nb_conda_kernels
  - stata_kernel
  - plotly
  - nodejs
  - geocoder
  - html5lib
  - plotnine
  - ipympl
  - git
  - python-kaleido
  - numba
  - jupyter
  - jupyterlab
  - numpy
  - openpyxl
  - jinja2
  - r
  - r-base
  - r-dplyr
  - r-tidyverse
  - r-essentials
  - r-easypackages
  - r-binsreg
  - r-data.table
  - r-renv
  - r-ggplot2
  - r-remotes
  - rpy2
  - pip:
      - geonamescache
      - stargazer
      - ipystata
      - pyfixest
      - isounidecode
      - binsreg
      - rdrobust 
      - lets-plot
